const isDev = process.env.NODE_ENV === 'development';

export default {
    ROULETTE_MIN_BET: 5,
    ROULETTE_MAX_BET: 300000,
    ROULETTE_TIMER: 20,
    ROULETTE_BETTING: "ROULETTE_BETTING",
    ROULETTE_IN_GAME: "ROULETTE_IN_GAME",
    ROULETTE_REWARDS: "ROULETTE_REWARDS",

    ROULETTE_COLOR_PINK: "ROULETTE_COLOR_PINK",
    ROULETTE_COLOR_GREEN: "ROULETTE_COLOR_GREEN",
    ROULETTE_COLOR_GREY: "ROULETTE_COLOR_GREY"
}